website/views/home.py
from flask import render_template, request, Blueprint, redirect, current_app, url_for, flash, session, jsonify, make_response
from flask_login import login_user, current_user, logout_user, login_required
from website import db
from website.models import Product, User, Bio, Contact, Order
import io 
import base64
from PIL import Image
import os
from collections import defaultdict
import json
import simplejson
import requests
import time
import random


main = Blueprint('main', __name__)
                                                         ### HOME PAGE
##########################################################################################

@main.route("/home", methods=['GET', 'POST'])
@login_required
def home():
   try:
      products_list = Product.query.filter_by(user_id=current_user.id).all()
      buyed = Order.query.filter_by(user_id=current_user.id).all()
      selled = Order.query.filter_by(seller_id=current_user.id).all()
      result = defaultdict(lambda: {'product': '', 'quantity': 0, })
      sum_ord = []
     
     
      if len(session['CART']) > 0:
         for i in session['CART']:
            
            key = '{}'.format(i["product"])
            result[key]["product"] = i["product"]
            result[key]["quantity"] += i["quantity"]
            sum_ord = list(result.values())
      else:
         print('session cart empty')
      cart = []
      if len(sum_ord) > 0:
         for o in sum_ord:
            product = Product.query.filter_by(id=o["product"]).first()
            s = product.seller
            
            cart.append({
               'order_id': ''.join(random.choice('qwertzuiopasdfghjklyxcvbnm1234567890') for i in range(30)),
               'quantity':o['quantity'],
               'buyer':current_user.id,
               'product': {
                  'product_id':product.id,
                  'product_name':product.name,
                  'product_price':product.price,
                  'product_require_file':product.require_file
                  },
               'seller':{
                  'seller_id':s.id,
                  'seller_username':s.username,
                  #'seller_wallet':s.contact.wallet 
                  }
               }
            )
            
         else:
            print('Some error wrong loading product data')
      else:
         print('Cart empty')
      session['BOX'] = cart
   except:
      pass
   finally:

      if request.method == 'POST':
         ord_address = request.form.get('order_address')
         ord_email = request.form.get('order_email_field')
         ord_tel = request.form.get('order_tel')
         ord_pin = request.form.get('order_pin')
         ord_wallet = request.form.get('order_wallet')
         
         for i in session['BOX']:
            p_id = i['product']['product_id']
            s = i['seller']['seller_id']
            if i['product']['product_require_file']:
               myfile = request.files[f'file-{p_id}']
               name = myfile.filename
               user_folder =  current_app.config["UPLOAD_FOLDER"] + '/' + str(current_user.id) + '/'+ 'orders_file' +'/'
               path = os.path.join(user_folder, name )
               if not name:
                  flash('For this product are required some file media', category="error")
                  break
               myfile.save(path)
               order = Order(product_id=p_id, pin=i['order_id'], user_id=current_user.id,seller_id=s,address=ord_address, email=ord_email,tel=ord_tel,wallet=ord_wallet,quantity=i['quantity'], files=name)
            else:
               order = Order(product_id=p_id, pin=i['order_id'], user_id=current_user.id,seller_id=s,address=ord_address, email=ord_email,tel=ord_tel,wallet=ord_wallet,quantity=i['quantity'])
            db.session.add(order)  
            db.session.commit()
         session['CART'] = []
         session['BOX'] = []
         cart = []

         flash('Order registered successfully', category='success')

         
   return render_template('home.html',user=current_user,user_products=products_list,cart=session['BOX'],buyed=buyed)
                                                    ####### PRODUCT DELETE
############################################################################
@main.route("/product/<p_id>/delete", methods=['GET','POST'])
@login_required
def product_delete(p_id):
   if request.method == 'GET':
      
      prodeuct_to_delete = Product.query.filter_by(id=p_id).first()
      
      prodeuct_to_delete.DELETED = 1
      db.session.commit()
      flash('Product deleted', category="success")
   else:
      flash('some error wrong deleted this product', category="error")
   
   return redirect(url_for('main.home'))
                                                      ##### SELLED
#######################################################################

website/views/homeInfo.py
from flask import render_template, request, Blueprint, redirect, current_app, url_for, flash, session, jsonify, make_response
from flask_login import login_user, current_user, logout_user, login_required
from website import db
from website.models import Product, User, Bio, Contact, Order

homeInfo = Blueprint('homeInfo', __name__)

@homeInfo.route('/home/selled', methods=['GET', 'POST'])
@login_required
def infoSelled():
   selled = Order.query.filter_by(seller_id=current_user.id).all()

   return render_template('infoSelled.html', user=current_user,cart=session['BOX'],selled=selled)



@homeInfo.route('/home/buyed', methods=['GET', 'POST'])
@login_required
def infoBuyed():

   buyed = Order.query.filter_by(user_id=current_user.id).all()
   
   return render_template('infoBuyed.html', user=current_user,buyed=buyed,cart=session['BOX'])


@homeInfo.route('/home/product', methods=['GET', 'POST'])
@login_required
def infoProduct():
   
   product = Product.query.filter_by(user_id=current_user.id).all()
   return render_template('infoProduct.html', user=current_user,user_products=product,cart=session['BOX'])

website/views/productView.py
from flask import render_template, request, Blueprint, redirect, current_app, url_for, flash, session, jsonify, make_response
from flask_login import login_user, current_user, logout_user, login_required
from website import db
from website.models import Product, User, Bio, Contact, Order

productView = Blueprint('productView', __name__)

@productView.route("/product/<id>", methods=['GET', 'POST'])
@login_required
def product_view(id):
   product = Product.query.filter_by(id=id).first()
   seller = product.seller
   if request.method == 'POST':
      if 'form_name' in request.form :
         name = request.form.get('input_fieldName')
         if name:
            product.name = name
            db.session.commit()
            flash('Product name changed', category="success")
         else:
            flash('Error, product name can not be empty', category='error')
      elif 'form_description' in request.form :
         description = request.form.get('input_fieldDescription')
         if description:
            product.description = description
            db.session.commit()
            flash('Product description changed', category="success")
         else:
            flash('Error, product description is empty', category='error')
      elif 'form_price' in request.form :
         price = request.form.get('input_fieldPrice')
         if price:
            product.price = price
            db.session.commit()
            flash('Product price changed', category="success")
         else:
            flash('Error, product price can not be empty', category='error')
      elif 'buyNowSellerView' in request.form:
         qnt = request.form.get('p_qnt')
         code = request.form.get('p_code')

         if not qnt:
            flash('No product selected', category="error")
         else:
            selected = {'product': code, 'quantity': int(qnt)}
            session['CART'].append(selected)
            flash('Product added to cart', category="success")
      else:
         redirect(404)
   return render_template('product_view.html', user=current_user, prod = product, seller=seller)
  

website/views/sellerView.py
from flask import render_template, request, Blueprint, redirect, current_app, url_for, flash, session, jsonify, make_response
from flask_login import login_user, current_user, logout_user, login_required
from website import db
from website.models import Product, User, Bio, Contact, Order

sellerView = Blueprint('sellerView', __name__)

@sellerView.route("/seller/<seller_name>", methods=['GET', 'POST'])
@login_required
def seller_view(seller_name):

   seller = User.query.filter_by(username=seller_name).first()
   products_seller = Product.query.filter_by(seller=seller).order_by(Product.date_posted.desc())
   bio = Bio.query.filter_by(author=seller).first()
   contact_seller = Contact.query.filter_by(user_contact=seller).first()
   if request.method == 'POST':
      if 'buyNowSellerView' in request.form:
         qnt = request.form.get('qnt')
         code = request.form.get('code')

         if not qnt:
            flash('No product selected', category="error")
         else:
            selected = {'product': code, 'quantity': int(qnt)}
            session['CART'].append(selected)
            flash('Product added to cart', category="success")
         return redirect(url_for('main.home'))
            
            
   return render_template('seller_view.html', user=current_user, seller=seller, seller_prod=products_seller, bio=bio,contact=contact_seller)
  

website/views/shop.py
from flask import render_template, request, Blueprint, redirect, url_for, current_app, flash,session
from flask_login import current_user
from website.models import Product, User
from country_list import countries_for_language
from collections import defaultdict
import random

countries = dict(countries_for_language('en'))

shopPage = Blueprint('shopPage', __name__)

@shopPage.route("/", methods=['GET', 'POST'])
@shopPage.route("/shop", methods=['GET', 'POST'])
def shop():
    row = list()
    countr = current_app.config["COUNTRIES"]#countries
    result = defaultdict(lambda: {'product': '', 'quantity': 0, })
    CATEGORY = current_app.config["CATEGORY_PRODUCT"]
    try:
        row = Product.query.filter_by(DELETED=False).all()
        
    except:
        pass
    finally:
        if request.method == 'POST':
            if 'filter' in request.form:
                country_selected = request.form.get('country_value')
                category_selected = request.form.get('category_value')
                filter_product = []
                if category_selected or country_selected:
                    filter_category = Product.query.filter_by(DELETED=False,category=category_selected).all()
                    filter_user =  User.query.filter_by(DELETED=False,country=country_selected).all()

                    for i in filter_category:
                        filter_product.append(i)

                    for i in filter_user:
                        p = i.products
                        for i in p:
                            filter_product.append(i)
                    row = filter_product
                else:
                    flash('No filters selected.', category='error')
                    
                return render_template('shop.html', prod= filter_product, user=current_user, country=countr, category=CATEGORY)
            elif 'buy_now' in request.form:
                qnt = request.form.get('qnt')
                code = request.form.get('code')
                if not qnt:
                    flash('No product selected', category="error")
                else:
                    
                    result['product'] = code
                    result['quantity'] = int(qnt)
                    session['CART'].append(result)
                    flash('Product added to cart', category="success")
            else:
                redirect(404)
    

    return render_template('shop.html', prod=row, user=current_user, country=countr, category=CATEGORY)

website/templates/authenticate.html
{% extends "home.html" %} {% block title %}Authenticate your account{% endblock %}
{% block authenticate_view%}
<div class="col font p-3 pt-0">
<h3 class="fs-4">Authenticate your account</h3>

<form method="POST">
    <div id="auth_email" class="row d-flex justify-content-center form-group ps-2 ">
        <label for="authenticate_email">Insert your email</label>
        <input type="email" name="authenticate_email" class="form-control w-3">
        <input type="submit" value="Submit" onclick="framecheck()" name="submit_authenticate_email" class="w-1 btn btn-outline-primary ms-2">
    </div>
    <div class="row form-group d-flex justify-content-center">
        <label for="authenticate_code">Insert your code</label>
        <input type="number" name="authenticate_code" class="form-control w-1">
        <input type="submit" value="Submit" name="submit_authenticate_code" class="w-1 btn btn-outline-primary ms-2">
    </div>    
</form>

<span translate="no">
    <img src="{{ url_for('static', filename='ico/email.svg')}}" style="filter:invert(100%);">
    </img>
    <a href="mailto:infouserCryptoShop@gmail.com" >Email to info service</a>
</span><br>
</div>

{% endblock %}

website/templates/bio.html
{% extends "index.html" %} {% block title %}Write your bio{% endblock %} 
{% block content %}
<div class="col p-3 m-auto">
    <form action="" method="post">
        <div class="form-group font" style="width: 100%;">
            <label for="bio_in"><h3>Write your bio:</h3></label>
            <textarea
                class="form-control border border-primary"
                id="bio_in"
                name="bio_in"
                placeholder="Enter a biographi about you and your mode to sell"               
                rows="5"
            ></textarea>
        </div><br>
        <div>
            <button type="submit" class="btn btn-primary ms-25">Add to Account</button>
        </div>
    </form>

</div>
{% endblock %}

website/templates/changelog.html
{% extends "index.html" %} {% block title %}ChangeLog{% endblock %} 
{% block content %}

<form class="w-50 p-3 text-center bolder m-auto" method="POST">
  <h3 align="center">Change password and user name</h3>
  <div class="form-group">
    <label for="cng_name_field">New username</label>
    <input
      type="text"
      class="form-control border border-primary"
      id="cng_name_field"
      name="cng_name_field"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
      <label for="old_pswd_field">Old Password</label>
      <input
        type="password"
        class="form-control border border-primary"
        id="old_pswd_field"
        name="old_pswd_field"
        placeholder="Enter password"
      />
    </div>
  <div class="form-group">
    <label for="cng_pswd1_field">New Password</label>
    <input
      type="password"
      class="form-control border border-primary"
      id="cng_pswd1_field"
      name="cng_pswd1_field"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="cng_pswd2_field">Repeat password</label>
    <input
      type="password"
      class="form-control border border-primary"
      id="cng_pswd2_field"
      name="cng_pswd2_field"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>


 
    
{% endblock %}
    

website/templates/createProduct.html
{% extends "index.html" %} {% block title %}Create Product{% endblock %} 
{% block content %}

<form class="w-50 p-3 text-center bolder m-auto" method="POST" enctype="multipart/form-data">
    <h3 align="center">Create your product</h3>
    <div class="form-group">
        <label for="product_name">Name</label>
        <input
            type="text"
            class="form-control border border-primary"
            id="product_name"
            name="product_name"
            placeholder="Enter a name for your product"
        />
    </div>
    <div class="form-group">
        <label for="product_description">Description</label>
        <textarea
            class="form-control border border-primary"
            id="product_description"
            name="product_description"
            placeholder="Enter a product description"
            cols="22"
            rows="2"
        ></textarea>
    </div>
    <div class="form-group" style="text-align: left;">
        <label for="product_price">Price</label>
        <input
            type="number"
            class="form-control border border-primary"
            id="product_price"
            name="product_price"
            style="width: 17vw;"
        />
    </div>
    <div class="form-group">
        <label for="product_photo">Some photo</label>
        <input
            type="file"
            class=""
            id="product_photo"
            name="product_photo"
            multiple
        />
    </div>
    <div class="form-group">
        <label for="product_category">Product</label>
        <select
            class="form-control border border-primary"
            id="product_category"
            name="product_category">
            {% for i in product_category %}
            <option value="{{ i }}">{{ i }}</option>
            {% endfor %}
        </select>
    </div>
    <br />
    <div class="form-group ">
        <label for="required_file" class="">Require file for this product?</label>
        <input name="required_file" id="required_file"class="form-check-input ms-1" type="checkbox" value="">
    </div>
    <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>


 
    
{% endblock %}

website/templates/getWallet.html
{% extends "home.html" %} {% block title %}Get Wallet{% endblock %} 
{% block getWallet %}
<div class="row lightgrey  font">
    <h3>Subscribe your wallet's</h3>
</div>
<br>
<div class="col-auto m-auto">
    <form action="" method="POST" align="center" class="position-relative col m-auto">
        <div class="row p-1">
            <div class="col form-floating">
                <input 
                    type="text"
                    class="mt-0 mb-1 pb-0 form-control fs-s w-3 h-100"
                    id="wallet_field"
                    name="wallet_field"
                    placeholder="Wallet"
                >
                <label for="wallet_field" class="pb-0 mb-0 ms-2 mt-1 pt-1 fs-xs">Wallet :</label>
                
            </div>
            <div class="col form-floating">
                
                <input 
                    type="text"
                    class=" mb-1 pb-0 form-control w-1xs fs-s h-100"
                    id="currency_field"
                    name="currency_field"
                    placeholder="Currency"
                >
                <label for="currency_field" class="ms-2 mt-1 mb-0 pt-1 fs-xs">Currency :</label>
            </div>
            <input class="btn btn-outline-success w-1xs" type="submit" name="addOldWallet" value="Add">
        </div><br>
        <div class="hstack justify-content-center">
            <select name="currency_selector" id="currency_selector" class="w-1 form-select">
                {% for i in currency%}
                <option class="font" value="{{i}}">{{i}}</option>
                {% endfor%}
            </select>
            <input type="submit" name="submitWallet" class="btn w-1 btn-outline-success" value="Get">
        </div>
    </form>
</div>
<br>
<br>

{% endblock%}

website/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link 
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" 
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" 
      crossorigin="anonymous"/>
    
    <link rel="stylesheet" href="{{ url_for('static', filename= 'style.css')}}"/>
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav  class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg sticky-top">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse bg-base mt-2" id="navbar">
        <div class="navbar-nav" >
          <a class="nav-item nav-link " id="shop" href="/shop"><em><b class="text-primary">Shop</b></em></a>
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="logout" href="/logout"><em><b class="text-primary">Logout</b></em></a>
          <a class="nav-item nav-link " id="home" href="/home"><em><b class="text-primary">Home</b></em></a>
         {% else %}
          <a class="nav-item nav-link" id="login" href="/login"><em><b class="text-primary">Login</b></em></a>
          {% endif %}

        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    {% if user.is_authenticated %}
    <div class="offcanvas offcanvas-start bg-base"  tabindex="-1" id="userSetting" aria-labelledby="offcanvasBottomLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body small">
        <div class="row p-2">
          <button onclick="show_cart()" class="h-o shadow btn p-2 btn btn-outline-info w-1"><b class="fw-bolder">Cart</b></button>     
        </div>
        <hr>
        <div class="row p-2">
          <a href="{{ url_for('utils.product') }}" class="h-o shadow btn p-2 btn btn-outline-success w-2"><b class="fw-bolder">Create Product</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('homeInfo.infoProduct') }}" class="h-o shadow btn p-2 btn btn-outline-info w-2"><b class="fw-bolder">Product</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('homeInfo.infoBuyed') }}" class="h-o shadow btn p-2 btn btn-outline-info w-2"><b class="fw-bolder">Buyed</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('homeInfo.infoSelled') }}" class="h-o shadow btn p-2 btn btn-outline-info w-2"><b class="fw-bolder">Selled</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('utils.getWallet') }}" class="h-o shadow btn p-2 btn btn-outline-warning w-2"><b class="fw-bolder">Get wallet</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('utils.bio') }}" class="h-o shadow btn p-2 btn btn-outline-warning w-2"><b class="fw-bolder">Write your bio</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('utils.contact') }}" class="h-o shadow btn p-2 btn btn-outline-warning w-2"><b class="fw-bolder">Add contact mode</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('utils.photo_user') }}" class="h-o shadow btn p-2 btn btn-outline-warning w-2"><b class="fw-bolder">Add photo user</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('utils.authenticate') }}" class="h-o shadow btn p-2 btn btn-outline-success w-2"><b class="fw-bolder">Authenticate</b></a>
        </div>
        <div class="row p-2">
          <a href="{{ url_for('change_log.changelog') }}" class="h-o shadow btn p-2 btn btn-outline-danger w-2"><b class="fw-bolder"> Change Password</b></a>
        </div>
      </div>
    </div>
    {% endif %}
    <div class="row">
      <div class="col-9 p-2"><br>
        {% block content %} {% endblock %}
      </div><br>


      <div id="news_vertical" class="col-3 container" style=" background-color:#2f2f2f;">
        
        
        <div id="news_f" class="row p-1 hgh3">
          <iframe src="https://www.jstor.org/stable/30078681">
          </iframe>
        </div>
        <div id="news_f" class="row p-1 hgh3">
          <iframe src="https://www.jstage.jst.go.jp/article/massspec1953/14/3/14_3_105/_article/-char/en" ">
          </iframe>
        </div>
        <div id="news_f" class="row p-1 hgh3">
          <iframe src="https://www.vettix.org" >
          </iframe>
        </div>
        
      </div>
    </div>
    
      <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>

    
  </body>
</html>

website/templates/infoProduct.html
{% extends "home.html" %} {% block title %}Home info product{% endblock %}
{% block infoProduct%}

<!-- PRODUCTS USER DIV -->
<div id="product_list_div" name="product_list" class="row p-3">

    {% for i in user_products %}
    
    <div class="row p-2">
        <!-- PRODUCTS USER DIV PHOTOS -->
        <div class="col-3 shadow">
            <div id="carouselExample{{i.id}}" class="carousel slide">
                <div class="carousel-inner">
                    {% for p in i.photo %}
                    <div class="carousel-item active">
                        
                        <img src="{{ url_for('static', filename='images/' + i.seller.id|string + '/' + p) }}" class="c{{i.id}}"id="{{i.name}}"style="height: 9.5rem;width: 100%;"/> 
                    
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample{{i.id}}" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExample{{i.id}}" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <!-- PRODUCTS USER DIV DETAILS -->
        <div class="col-9 ps-1" style="height: 9.5rem;background-color:slategray;color:lightgray;">
            <div class="p-0 m-0">
                <h5>Name:{{ i.name[:27] }}</h5>
            </div>
            <div class="p-0" style=" margin-top:-.9em;">
                <em style="font-size: .85rem;">Description : {{ i.description[:77] }}</em>
                <br><p style="font-size: .7rem;">date of pubblication:{{ i.date_posted.strftime('%Y -%h -%d') }}</p>
            </div>
            <div style="margin-top: -1em;">
                <em>Cost :{{ i.price }}$ </em>
                
            </div>
            <div class="hstack gap-3 position-absolute top-0 end-0 p-3" >
                <!-- PRODUCTS USER SOW -->
                <button class="btn-outline-info p-0 shadow" style="width:2.5vw;height: 5.3vh;">
                    <a href="/product/{{i.id}}"><img src="{{ url_for('static', filename='ico/arrow.svg')}}"style="width:3.3vw;height: 4.7vh;border-radius:50%;margin-left:-.9em;"></img>
                    </a>
                </button>
            
                <!-- PRODUCTS USER DELETE -->
                <button class="btn-outline-info p-0 shadow " style="width:2.5vw;height: 5.7vh;">
                    <a href="/product/{{i.id}}/delete"><img src="{{ url_for('static', filename='ico/trash.svg')}}"style="width:3.3vw;height:4.4vh;border-radius:50%;margin-left:-.7em;"></img>
                    </a>
                </button>
            </div>
        </div>
    </div><br>
    {% else %}
    <h4 class="font">No products to show</h4>
    {% endfor %}
</div>

{% endblock %}

website/templates/login.html
{% extends "index.html" %} {% block title %}Login{% endblock %} 
{% block content %}

<form class="w-50 p-3 text-center bolder" method="POST" style="margin: auto">
  <h3 align="center">Login</h3>
  <div class="form-group">
      <label for="username_log_field">User Name</label>
      <input
        type="text"
        class="form-control border border-primary"
        id="username_log_field"
        name="username_log_field"
        placeholder="Enter your username"
      />
  </div>
  <div class="form-group">
    <label for="password_log_field">Password</label>
    <input
      type="password"
      class="form-control border border-primary"
      id="password_log_field"
      name="password_log_field"
      placeholder="Enter password"
    />
  </div>
  <br/>
  <button type="submit" name="login" class="btn btn-primary">Submit</button><br>
  <em>Don't have an account?<br>
  Create one <a href="/signin">Here</a></em>
</form>

{% endblock%}

website/templates/newWallet.html
{% extends "home.html" %} {% block title %}New Wallet{% endblock %} 
{% block getWallet %}
<h1>
    new Wallet
</h1>
{% endblock %}

website/templates/photo_user.html
{% extends "index.html" %} {% block title %}Account Home{% endblock %}
{% block content%}
<div class="row m-auto p-1">
    <form class="w-50 p-3 text-center bolder m-auto" method="POST" enctype="multipart/form-data">
        <h3 align="center">Upload your user image</h3>
        <div class="form-group">
            <label for="photo_user">Select one photo</label>
            <input
                type="file"
                class="form-control border border-primary"
                id="photo_user"
                name="photo_user"
            />
        </div>
        <button type="submit" name="photo_user_submit" class="btn btn-primary">Submit</button>
    </form>
    
</div>

{% endblock %}